<?php
/**
 * Custom Field Functions
 *
 * @package    Core_Functionality
 * @subpackage Core_Functionality\Includes
 * @since      0.1.0
 * @license    GPL-2.0+
 */

/**
 * Register Post 2 Post Relationships
 *
 * @link https://wordpress.org/plugins/posts-to-posts/
 *
 * @return void
 */
function core_post_connections_translation() {
  p2p_register_connection_type( array(
    'name'  => 'help_translations',
    'from'  => 'kbe_knowledgebase',
    'to'    => 'kbe_knowledgebase',
  	'reciprocal'   => true,
    'admin_column' => 'any',
    'title' => array(
    'from' => __( 'Translations', 'core-functionality' ),
      'to' => __( 'Translations', 'core-functionality' )
    ),
    'from_labels' => array(
      'singular_name'   => __( 'Article', 'core-functionality' ),
      'search_items'    => __( 'Search articles', 'core-functionality' ),
      'not_found'       => __( 'No articles found.', 'core-functionality' ),
      'create'          => __( 'Add a Translation', 'core-functionality' ),
    ),
    'to_labels' => array(
      'singular_name'   => __( 'Article', 'core-functionality' ),
      'search_items'    => __( 'Search articles', 'core-functionality' ),
      'not_found'       => __( 'No articles found.', 'core-functionality' ),
      'create'          => __( 'Add a Translation', 'core-functionality' ),
    ),
  ) );

  p2p_register_connection_type( array(
    'name'  => 'campaign_translations',
    'from'  => 'campaign',
    'to'    => 'campaign',
    'reciprocal' => true,
    'admin_column' => 'any',
    'title' => array(
    'from' => __( 'Translations', 'core-functionality' ),
      'to' => __( 'Translations', 'core-functionality' )
    ),
    'from_labels' => array(
      'singular_name'   => __( 'Campaign', 'core-functionality' ),
      'search_items'    => __( 'Search campaigns', 'core-functionality' ),
      'not_found'       => __( 'No campaigns found.', 'core-functionality' ),
      'create'          => __( 'Add a Translation', 'core-functionality' ),
    ),
    'to_labels' => array(
      'singular_name'   => __( 'Campaign', 'core-functionality' ),
      'search_items'    => __( 'Search campaigns', 'core-functionality' ),
      'not_found'       => __( 'No campaigns found.', 'core-functionality' ),
      'create'          => __( 'Add a Translation', 'core-functionality' ),
    ),
  ) );

  p2p_register_connection_type( array(
    'name'  => 'post_translations',
    'from'  => 'post',
    'to'    => 'post',
    'reciprocal' => true,
    'admin_column' => 'any',
    'title' => array(
    'from' => __( 'Translations', 'core-functionality' ),
      'to' => __( 'Translations', 'core-functionality' )
    ),
    'from_labels' => array(
      'singular_name'   => __( 'Post', 'core-functionality' ),
      'search_items'    => __( 'Search posts', 'core-functionality' ),
      'not_found'       => __( 'No posts found.', 'core-functionality' ),
      'create'          => __( 'Add a Translation', 'core-functionality' ),
    ),
    'to_labels' => array(
      'singular_name'   => __( 'Post', 'core-functionality' ),
      'search_items'    => __( 'Search posts', 'core-functionality' ),
      'not_found'       => __( 'No posts found.', 'core-functionality' ),
      'create'          => __( 'Add a Translation', 'core-functionality' ),
    ),
  ) );

  p2p_register_connection_type( array(
    'name'  => 'page_translations',
    'from'  => 'page',
    'to'    => 'page',
    'reciprocal' => true,
    'admin_column' => 'any',
    'title' => array(
    'from' => __( 'Translations', 'core-functionality' ),
      'to' => __( 'Translations', 'core-functionality' )
    ),
    'from_labels' => array(
		'singular_name'   => __( 'Page', 'core-functionality' ),
		'search_items'    => __( 'Search pages', 'core-functionality' ),
		'not_found'       => __( 'No pages found.', 'core-functionality' ),
		'create'          => __( 'Add a Translation', 'core-functionality' ),
    ),
    'to_labels' => array(
      'singular_name'   => __( 'Page', 'core-functionality' ),
      'search_items'    => __( 'Search pages', 'core-functionality' ),
      'not_found'       => __( 'No pages found.', 'core-functionality' ),
      'create'          => __( 'Add a Translation', 'core-functionality' ),
    ),
  ) );

}
add_action( 'p2p_init', 'core_post_connections_translation' );

/**
 * Register Custom Meta Fields For Gutenberg
 *
 * @return void
 */
function core_register_post_meta() {
	$args = array(
		'single' 			=> true,
		'show_in_rest' 		=> true,
		'description'  		=> __( 'Enter an internal title, which will only be seen on adminstration pages..', 'core-functionality' ),
		'type' 				=> 'string'
	);
	register_post_meta( '', 'internal-title', $args );
}
add_action( 'init', 'core_register_post_meta' );

/**
 * Register Custom Fields
 *
 * @link https://www.advancedcustomfields.com/resources/register-fields-via-php/
 *
 * @var void
 */
if( function_exists( 'acf_add_local_field_group' ) ) {

	acf_add_local_field_group( array(
		'key' => 'group_5c7ee3ef5b02a',
		'title' => __( 'Internals', 'core-functionality' ),
		'fields' => array(
			array(
				'key' => 'field_5c7eebe648efb',
				'label' => __( 'Internal Title', 'core-functionality' ),
				'name' => 'internal-title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'campaign',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'program',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'kbe_knowledgebase',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group( array(
		'key' => 'group_5b9f2b166ef63',
		'title' => __( 'Campaign Details', 'core-functionality' ),
		'fields' => array(
			array(
				'key' => 'field_5b9f2b1e8c378',
				'label' => __( 'Campaign Status', 'core-functionality' ),
				'name' => 'campaign_status',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'campaign-status',
				'field_type' => 'select',
				'allow_null' => 0,
				'add_term'   => 0,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array(
				'key' => 'field_5ba277a381afd',
				'label' => __( 'Campaign Category', 'core-functionality' ),
				'name' => 'campaign_category',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'campaign-category',
				'field_type' => 'select',
				'allow_null' => 0,
				'add_term'   => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array(
				'key' => 'field_5be1d774dpgh',
				'label' => __( 'Primary Page', 'core-functionality' ),
				'name' => 'is-primary',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => __( 'Yes', 'core-functionality' ),
				'ui_off_text' => __( 'No', 'core-functionality' ),
			),
			array(
				'key' => 'field_5be1d774d6147',
				'label' => __( 'Featured on Home', 'core-functionality' ),
				'name' => 'is-featured',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => __( 'Yes', 'core-functionality' ),
				'ui_off_text' => __( 'No', 'core-functionality' ),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'campaign',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'categories',
			1 => 'tags',
		),
		'active' => 1,
		'description' => '',
	));

  /* Campaign Category - Replace Default Metabox with Single Select Field */
	acf_add_local_field_group( array(
		'key' => 'group_5bddf95ccf0a1',
		'title' => __( 'Campaign Category', 'core-functionality' ),
		'fields' => array(
			array(
				'key' => 'field_5bddf97d57d5f',
				'label' => __( 'Campaign Category', 'core-functionality' ),
				'name' => 'campaign_category',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy'   => 'campaign-category',
				'field_type' => 'select',
				'allow_null' => 1,
				'add_term'   => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			array(
					'param' => 'page_type',
					'operator' => '!=',
					'value' => 'front_page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	/* Event Category - Replace Default Metabox with Single-select Field */
	acf_add_local_field_group( array(
		'key' => 'group_5be0ee1b9ffb4',
		'title' => __( 'Event Category', 'core-functionality' ),
		'fields' => array(
			array(
				'key' => 'field_5be0ee230544e',
				'label' => __( 'Event Category', 'core-functionality' ),
				'name' => 'event_category',
				'type' => 'taxonomy',
				'instructions' => __( 'Select an event category to associate with this item.', 'core-functionality' ),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'event-category',
				'field_type' => 'select',
				'allow_null' => 1,
				'add_term'   => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'campaign',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'program',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

  acf_add_local_field_group( array(
  	'key' => 'group_5b9f2a1c2783f',
  	'title' => __( 'Campaign CTA', 'core-functionality' ),
  	'fields' => array(
  		array(
  			'key' => 'field_5bce20f70b78f',
  			'label' => __( 'Action Text', 'core-functionality' ),
  			'name' => 'action_text',
  			'type' => 'wysiwyg',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'tabs' => 'all',
  			'toolbar' => 'basic',
  			'media_upload' => 0,
  			'delay' => 0,
  		),
  		array(
  			'key' => 'field_5bce210e0b790',
  			'label' => __( 'Action Links', 'core-functionality' ),
  			'name' => 'links',
  			'type' => 'repeater',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'collapsed' => 'field_5bce212b0b791',
  			'min' => 0,
  			'max' => 0,
  			'layout' => 'row',
  			'button_label' => __( 'Add Action Link', 'core-functionality' ),
  			'sub_fields' => array(
  				array(
  					'key' => 'field_5bce21330b792',
  					'label' => __( 'Link', 'core-functionality' ),
  					'name' => 'link',
  					'type' => 'link',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'return_format' => 'array',
  				),
  			),
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'campaign',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

  /* Event Fields */
  acf_add_local_field_group(array(
  	'key' => 'group_5bce612392921',
  	'title' => __( 'Event Detail', 'core-functionality' ),
  	'fields' => array(
  		array(
  			'key' => 'field_5bce613153c2d',
  			'label' => 'Link',
  			'name' => 'link',
  			'type' => 'link',
  			'instructions' => __( 'Add link to event detail.', 'core-functionality' ),
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'return_format' => 'array',
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'event',
  			),
  		),
      array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'event-recurring',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

	/* Home Page Sections */
	/* Hero */
	acf_add_local_field_group( array(
		'key' => 'group_5bbbb7c0da03a',
		'title' => __( 'Hero Section', 'core-functionality' ),
		'fields' => array(
			array(
				'key' => 'field_5bbbb811020a5',
				'label' => __( 'Title', 'core-functionality' ),
				'name' => 'title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bc763c739ca2',
				'label' => __( 'Running Head', 'core-functionality' ),
				'name' => 'subtitle',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bbbb81b020a6',
				'label' => __( 'Content', 'core-functionality' ),
				'name' => 'content',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5bbbb7ea020a3',
				'label' => __( 'Image', 'core-functionality' ),
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5bbbb827020a7',
				'label' => __( 'Link', 'core-functionality' ),
				'name' => 'link',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
		),
		'location' => array(
  		array(
  			array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/page-home.php',
  			),
  		),
  	),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'discussion',
			4 => 'comments',
			5 => 'revisions',
			6 => 'slug',
			7 => 'author',
			8 => 'format',
			9 => 'featured_image',
			10 => 'categories',
			11 => 'tags',
			12 => 'send-trackbacks',
		),
		'active' => 1,
		'description' => '',
	));

  acf_add_local_field_group(array(
  	'key' => 'group_5bbbc5bcb59ff',
  	'title' => __( 'Home Page Sections', 'core-functionality' ),
  	'fields' => array(
  		array(
  			'key' => 'field_5bbbc5c99e4ce',
  			'label' => __( 'Sections', 'core-functionality' ),
  			'name' => 'sections',
  			'type' => 'flexible_content',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'layouts' => array(
					
  				'5bbbc62edc7d8' => array(
  					'key' => '5bbbc62edc7d8',
  					'name' => 'help_answers',
  					'label' => __( 'Help & Answers', 'core-functionality' ),
  					'display' => 'row',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_5bbbc71bd09d3',
  							'label' => __( 'Title', 'core-functionality' ),
  							'name' => 'title',
  							'type' => 'text',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'maxlength' => '',
  						),
  						array(
  							'key' => 'field_5bbbc735d09d4',
  							'label' => __( 'Categories', 'core-functionality' ),
  							'name' => 'categories',
  							'type' => 'taxonomy',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'taxonomy' => 'kbe_taxonomy',
  							'field_type' => 'multi_select',
  							'allow_null' => 0,
  							'add_term'   => 1,
  							'save_terms' => 1,
  							'load_terms' => 1,
  							'return_format' => 'id',
  							'multiple' => 0,
  						),
  						// array(
  						// 	'key' => 'field_5bbbc776f5daf',
  						// 	'label' => __( 'Background Color', 'core-functionality' ),
  						// 	'name' => 'background_color',
  						// 	'type' => 'color_picker',
  						// 	'instructions' => '',
  						// 	'required' => 0,
  						// 	'conditional_logic' => 0,
  						// 	'wrapper' => array(
  						// 		'width' => '',
  						// 		'class' => '',
  						// 		'id' => '',
  						// 	),
  						// 	'default_value' => '',
  						// ),
  						array(
  							'key' => 'field_5bbbc708d09d2',
  							'label' => __( 'Icon', 'core-functionality' ),
  							'name' => 'icon',
  							'type' => 'image',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'return_format' => 'id',
  							'preview_size' => 'thumbnail',
  							'library' => 'all',
  							'min_width' => '',
  							'min_height' => '',
  							'min_size' => '',
  							'max_width' => '',
  							'max_height' => '',
  							'max_size' => '',
  							'mime_types' => '',
  						),
  					),
  					'min' => '',
  					'max' => '',
					),
					
  				'layout_5bbbc82795035' => array(
  					'key' => 'layout_5bbbc82795035',
  					'name' => 'programs',
  					'label' => __( 'Programs', 'core-functionality' ),
  					'display' => 'row',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_5bbbc84695036',
  							'label' => __( 'Title', 'core-functionality' ),
  							'name' => 'title',
  							'type' => 'text',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'maxlength' => '',
  						),
  						array(
  							'key' => 'field_5bbbc85095037',
  							'label' => __( 'Programs', 'core-functionality' ),
  							'name' => 'programs',
  							'type' => 'repeater',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'collapsed' => 'field_5bbbd147f8920',
  							'min' => 0,
  							'max' => 5,
  							'layout' => 'row',
  							'button_label' => __( 'Add Program', 'core-functionality' ),
  							'sub_fields' => array(
  								array(
  									'key' => 'field_5bbbd147f8920',
  									'label' => __( 'Title', 'core-functionality' ),
  									'name' => 'title',
  									'type' => 'text',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => '',
  									'placeholder' => '',
  									'prepend' => '',
  									'append' => '',
  									'maxlength' => '',
  								),
  								array(
  									'key' => 'field_5bbbd14ef8921',
  									'label' => __( 'Content', 'core-functionality' ),
  									'name' => 'content',
  									'type' => 'wysiwyg',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => '',
  									'tabs' => 'all',
  									'toolbar' => 'basic',
  									'media_upload' => 1,
  									'delay' => 0,
  								),
  								array(
  									'key' => 'field_5bbbe401be28c',
  									'label' => __( 'Program', 'core-functionality' ),
  									'name' => 'link',
  									'type' => 'relationship',
  									'instructions' => __( 'Select the related program.', 'core-functionality' ),
  									'required' => 1,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
                    'post_type' => array(
              				0 => 'program',
              				1 => 'page',
              			),
  									'taxonomy' => '',
  									'filters' => array(
  										0 => 'search',
  									),
  									'elements' => '',
  									'min' => '',
  									'max' => '',
  									'return_format' => 'object',
  								),
  								array(
  									'key' => 'field_5bbbd169f8923',
  									'label' => __( 'Icon', 'core-functionality' ),
  									'name' => 'icon',
  									'type' => 'image',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'return_format' => 'id',
  									'preview_size' => 'thumbnail',
  									'library' => 'all',
  									'min_width' => '',
  									'min_height' => '',
  									'min_size' => '',
  									'max_width' => '',
  									'max_height' => '',
  									'max_size' => '',
  									'mime_types' => '',
  								),
  							),
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  				'layout_5bbbe397ef160' => array(
  					'key' => 'layout_5bbbe397ef160',
  					'name' => 'content_links',
  					'label' => __( 'Content Links', 'core-functionality' ),
  					'display' => 'row',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_5bbbe397ef161',
  							'label' => __( 'Title', 'core-functionality' ),
  							'name' => 'title',
  							'type' => 'text',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'maxlength' => '',
  						),
  						array(
  							'key' => 'field_5bbbe397ef162',
  							'label' => __( 'Posts', 'core-functionality' ),
  							'name' => 'posts',
  							'type' => 'repeater',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'collapsed' => 'field_5bbbd03da00bb',
  							'min' => 0,
  							'max' => 0,
  							'layout' => 'block',
  							'button_label' => __( 'Add Block', 'core-functionality' ),
  							'sub_fields' => array(
  								array(
  									'key' => 'field_5bbbe397ef163',
  									'label' => __( 'Title', 'core-functionality' ),
  									'name' => 'title',
  									'type' => 'text',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => '',
  									'placeholder' => '',
  									'prepend' => '',
  									'append' => '',
  									'maxlength' => '',
  								),
  								array(
  									'key' => 'field_5bbbe397ef164',
  									'label' => __( 'Content', 'core-functionality' ),
  									'name' => 'content',
  									'type' => 'wysiwyg',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => '',
  									'tabs' => 'all',
  									'toolbar' => 'basic',
  									'media_upload' => 0,
  									'delay' => 0,
  								),
  								array(
  									'key' => 'field_5bbbe5ed88c06',
  									'label' => __( 'Post', 'core-functionality' ),
  									'name' => 'post',
  									'type' => 'page_link',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'post_type' => '',
  									'taxonomy' => '',
  									'allow_null' => 0,
  									'allow_archives' => 1,
  									'multiple' => 0,
  								),
  								array(
  									'key' => 'field_5bbbe397ef166',
  									'label' => __( 'Image', 'core-functionality' ),
  									'name' => 'image',
  									'type' => 'image',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'return_format' => 'array',
  									'preview_size' => 'thumbnail',
  									'library' => 'all',
  									'min_width' => '',
  									'min_height' => '',
  									'min_size' => '',
  									'max_width' => '',
  									'max_height' => '',
  									'max_size' => '',
  									'mime_types' => '',
  								),
  							),
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
          'layout_5bcbb92ee5437' => array(
            'key' => 'layout_5bcbb92ee5437',
            'name' => 'blocks',
            'label' => __( 'Flexible Blocks', 'core-functionality' ),
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_5bcbb92ee5438',
                'label' => __( 'Title', 'core-functionality' ),
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_5bcbb92ee5439',
                'label' => __( 'Blocks', 'core-functionality' ),
                'name' => 'blocks',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => 'field_5bbbd147f8920',
                'min' => 0,
                'max' => 4,
                'layout' => 'row',
                'button_label' => __( 'Add Block', 'core-functionality' ),
                'sub_fields' => array(
                  array(
                    'key' => 'field_5bdde0ef3d41d',
                    'label' => __( 'Format', 'core-functionality' ),
                    'name' => 'format',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'freeform' => __( 'Free-form', 'core-functionality' ),
                      'post' => __( 'Recent Post', 'core-functionality' ),
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5bcbb92ee543a',
                    'label' => __( 'Title', 'core-functionality' ),
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_5bcbb92ee543b',
                    'label' => __( 'Content', 'core-functionality' ),
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                      array(
                        array(
                          'field' => 'field_5bdde0ef3d41d',
                          'operator' => '==',
                          'value' => 'freeform',
                        ),
                      ),
                    ),
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                  ),
                  array(
                    'key' => 'field_5bcbb92ee543c',
                    'label' => __( 'Button', 'button' ),
                    'name' => 'button',
                    'type' => 'link',
                    'instructions' => __( 'Add button', 'core-functionality' ),
                    'required' => 0,
                    'conditional_logic' => array(
                      array(
                        array(
                          'field' => 'field_5bdde0ef3d41d',
                          'operator' => '==',
                          'value' => 'freeform',
                        ),
                      ),
                    ),
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                  array(
                    'key' => 'field_5bdde1f337a5f',
                    'label' => __( 'Post Type', 'core-functionality' ),
                    'name' => 'post_type',
                    'type' => 'posttype_select',
                    'instructions' => __( 'Select the type of post to display.', 'core-functionality' ),
                    'required' => 0,
                    'conditional_logic' => array(
                      array(
                        array(
                          'field' => 'field_5bdde0ef3d41d',
                          'operator' => '==',
                          'value' => 'post',
                        ),
                      ),
                    ),
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 'event',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                  ),
                  array(
                    'key' => 'field_5bcbb92ee543d',
                    'label' => __( 'Image', 'core-functionality' ),
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'id',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                  array(
              			'key' => 'field_5ba4000kitz',
              			'label' => __( 'Class', 'core-functionality' ),
              			'name' => 'class',
              			'type' => 'text',
              			'instructions' => '',
              			'required' => 0,
              			'conditional_logic' => 0,
              			'wrapper' => array(
              				'width' => '',
              				'class' => '',
              				'id' => '',
              			),
              			'default_value' => '',
              			'placeholder' => 'my-block-class',
              			'prepend' => '',
              			'append' => '',
              			'maxlength' => '',
              		),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
          ),
  				'layout_5bbbd2a6f8a3e' => array(
  					'key' => 'layout_5bbbd2a6f8a3e',
  					'name' => 'text_content',
  					'label' => __( 'Text Content', 'core-functionality' ),
  					'display' => 'row',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_5bbbd2baf8a3f',
  							'label' => __( 'Content', 'core-functionality' ),
  							'name' => 'content',
  							'type' => 'wysiwyg',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'tabs' => 'all',
  							'toolbar' => 'full',
  							'media_upload' => 1,
  							'delay' => 0,
  						),
  						array(
  							'key' => 'field_5bbbd2e9ac08f',
  							'label' => __( 'CSS Class', 'core-functionality' ),
  							'name' => 'css_class',
  							'type' => 'text',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => 'my-section-class',
  							'prepend' => '.css',
  							'append' => '',
  							'maxlength' => '',
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  				'layout_5bbbe20821dde' => array(
  					'key' => 'layout_5bbbe20821dde',
  					'name' => 'call_to_action',
  					'label' => __( 'Call to Action', 'core-functionality' ),
  					'display' => 'row',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_5bbbe21821ddf',
  							'label' => __( 'Title', 'core-functionality' ),
  							'name' => 'title',
  							'type' => 'text',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'maxlength' => '',
  						),
  						array(
  							'key' => 'field_5bbbe22121de0',
  							'label' => __( 'Content', 'content' ),
  							'name' => 'content',
  							'type' => 'wysiwyg',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'tabs' => 'all',
  							'toolbar' => 'basic',
  							'media_upload' => 0,
  							'delay' => 0,
  						),
  						array(
  							'key' => 'field_5bbbe23c21de1',
  							'label' => __( 'Link', 'core-functionality' ),
  							'name' => 'link',
  							'type' => 'link',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'return_format' => 'array',
  						),
  						array(
  							'key' => 'field_5bbbe25a21de2',
  							'label' => __( 'CSS Class', 'core-functionality' ),
  							'name' => 'css_class',
  							'type' => 'text',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => 'my-section-class',
  							'prepend' => '.css',
  							'append' => '',
  							'maxlength' => '',
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  				'layout_5bbbe7663c923' => array(
  					'key' => 'layout_5bbbe7663c923',
  					'name' => 'post_grid',
  					'label' => __( 'Post Grid', 'core-functionality' ),
  					'display' => 'row',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_5bbbe7743c924',
  							'label' => __( 'Title', 'core-functionality' ),
  							'name' => 'title',
  							'type' => 'text',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'maxlength' => '',
  						),
  						array(
  							'key' => 'field_5bbbe8bcdcf83',
  							'label' => __( 'Post Type', 'core-functionality' ),
  							'name' => 'post_type',
  							'type' => 'select',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'choices' => array(
  								'post' => __( 'Post', 'core-functionality' ),
  								'page' => __( 'Page', 'core-functionality' ),
  								'event' => __( 'Event', 'core-functionality' ),
  								'campaign' => __( 'Campaign', 'core-functionality' ),
                  'program'  => __( 'Program', 'core-functionality' ),
  								'kbe_knowledgebase' => __( 'Help & Answers', 'core-functionality' ),
  							),
  							'default_value' => array(
  							),
  							'allow_null' => 0,
  							'multiple' => 0,
  							'ui' => 0,
  							'return_format' => 'value',
  							'ajax' => 0,
  							'placeholder' => '',
  						),
  						array(
  							'key' => 'field_5bbbe7953c926',
  							'label' => __( 'Category', 'core-functionality' ),
  							'name' => 'category',
  							'type' => 'taxonomy',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => array(
  								array(
  									array(
  										'field' => 'field_5bbbe8bcdcf83',
  										'operator' => '==',
  										'value' => 'post',
  									),
  								),
  							),
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'taxonomy' => 'category',
  							'field_type' => 'multi_select',
  							'allow_null' => 1,
  							'add_term'   => 1,
  							'save_terms' => 0,
  							'load_terms' => 0,
  							'return_format' => 'id',
  							'multiple' => 0,
  						),
  						array(
  							'key' => 'field_5bbbe9c0f3278',
  							'label' => __( 'Category', 'core-functionality' ),
  							'name' => 'event_category',
  							'type' => 'taxonomy',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => array(
  								array(
  									array(
  										'field' => 'field_5bbbe8bcdcf83',
  										'operator' => '==',
  										'value' => 'event',
  									),
                    array(
  										'field' => 'field_5bbbe8bcdcf83',
  										'operator' => '==',
  										'value' => 'event-recurring',
  									),
  								),
  							),
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'taxonomy' => 'event-categories',
  							'field_type' => 'multi_select',
  							'allow_null' => 1,
  							'add_term'   => 1,
  							'save_terms' => 0,
  							'load_terms' => 0,
  							'return_format' => 'id',
  							'multiple' => 0,
  						),
  						array(
  							'key' => 'field_5bbbec502fbf0',
  							'label' => __( 'Category', 'core-functionality' ),
  							'name' => 'kb_category',
  							'type' => 'taxonomy',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => array(
  								array(
  									array(
  										'field' => 'field_5bbbe8bcdcf83',
  										'operator' => '==',
  										'value' => 'kbe_knowledgebase',
  									),
  								),
  							),
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'taxonomy' => 'kbe_taxonomy',
  							'field_type' => 'multi_select',
  							'allow_null' => 1,
  							'add_term'   => 1,
  							'save_terms' => 0,
  							'load_terms' => 0,
  							'return_format' => 'id',
  							'multiple' => 0,
  						),
  						array(
  							'key' => 'field_5bbbe964f3277',
  							'label' => __( 'Category', 'core-functionality' ),
  							'name' => 'campaign_category',
  							'type' => 'taxonomy',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => array(
  								array(
  									array(
  										'field' => 'field_5bbbe8bcdcf83',
  										'operator' => '==',
  										'value' => 'campaign',
  									),
  								),
  								array(
  									array(
  										'field' => 'field_5bbbe8bcdcf83',
  										'operator' => '==',
  										'value' => 'post',
  									),
  								),
  								array(
  									array(
  										'field' => 'field_5bbbe8bcdcf83',
  										'operator' => '==',
  										'value' => 'page',
  									),
  								),
  							),
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'taxonomy' => 'campaign-category',
  							'field_type' => 'multi_select',
  							'allow_null' => 1,
  							'add_term'   => 1,
  							'save_terms' => 1,
  							'load_terms' => 1,
  							'return_format' => 'id',
  							'multiple' => 0,
  						),
  						array(
  							'key' => 'field_5bbbebce936b4',
  							'label' => __( 'Number to Display', 'core-functionality' ),
  							'name' => 'posts_per_page',
  							'type' => 'number',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => 3,
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'min' => '',
  							'max' => 10,
  							'step' => '',
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  			),
  			'button_label' => __( 'Add Section', 'core-functionality' ),
  			'min' => '',
  			'max' => '',
  		),
  	),
  	'location' => array(
  		array(
  			array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/page-home.php',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => array(
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'discussion',
			4 => 'comments',
			5 => 'revisions',
			6 => 'slug',
			7 => 'author',
			8 => 'format',
			9 => 'featured_image',
			10 => 'categories',
			11 => 'tags',
			12 => 'send-trackbacks',
		),
  	'active' => 1,
  	'description' => '',
  ));

}

function core_remove_cpt_edit_group() {
  echo '<style type="text/css">
         h2.hndle.ui-sortable-handle a.acf-hndle-cog { display: none; visibility: hidden }
       </style>';
}

add_action( 'admin_head', 'core_remove_cpt_edit_group' );
